# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ili9882n/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM)/videox/


obj-y += ilitek_v3_node.o\
	ilitek_v3.o \
	ilitek_v3_flash.o \
	ilitek_v3_mtk.o \
	ilitek_v3_ic.o \
	ilitek_v3_touch.o \
	ilitek_v3_mp.o \
	ilitek_v3_i2c.o
	
