#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
obj-y := tekhw_common_lcm.o tekhw_common_lcm_gpio.o lcm_pmic.o

